=== colgreen/neat-yahoo-group-archive/files/NEAT XML/neat-run-output.xsd
<?xml version="1.0" encoding="UTF-8"?><xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">	<xs:complexType name="dynamicParameterType">		<xs:simpleContent>			<xs:extension base="xs:string">				<xs:attribute name="id" type="xs:token" use="required"/>			</xs:extension>		</xs:simpleContent>	</xs:complexType>	<xs:element name="neat-run-output">		<xs:complexType>			<xs:sequence>				<xs:element name="neat-run-info">					<xs:complexType>						<xs:sequence>							<xs:element name="author" type="xs:string"/>							<xs:element name="description" type="xs:string"/>						</xs:sequence>					</xs:complexType>				</xs:element>				<xs:element name="search-parameters" minOccurs="0">					<xs:complexType>						<xs:sequence>							<xs:element name="population-size" type="xs:integer"/>							<xs:element name="neuron-mutation-probability" type="xs:decimal"/>							<xs:element name="connect-mutation-probability" type="xs:decimal"/>							<xs:element name="weight-mutation-probability" type="xs:decimal"/>							<xs:element name="compatibility-threshold" type="xs:decimal"/>							<xs:element name="disjoint-coefficient" type="xs:decimal"/>							<xs:element name="excess-coefficient" type="xs:decimal"/>							<xs:element name="weightdelta-coefficient" type="xs:decimal"/>							<xs:element name="survival-proportion" type="xs:decimal"/>							<xs:element name="dynamic-parameter" type="dynamicParameterType" maxOccurs="unbounded"/>						</xs:sequence>					</xs:complexType>				</xs:element>				<xs:element name="domain-config" minOccurs="0">					<xs:complexType>						<xs:sequence>							<xs:element name="domain-id">								<xs:complexType>									<xs:simpleContent>										<xs:extension base="xs:string">											<xs:attribute name="id" type="xs:string" use="required"/>											<xs:attribute name="version" type="xs:decimal" use="required"/>											<xs:attribute name="authoreddate" type="xs:string" use="required"/>											<xs:attribute name="description" type="xs:string" use="optional"/>										</xs:extension>									</xs:simpleContent>								</xs:complexType>							</xs:element>							<xs:element name="domain-parameters">								<xs:complexType>									<xs:sequence>										<xs:element name="input-node-count" type="xs:short"/>										<xs:element name="output-node-count" type="xs:short"/>										<xs:element name="dynamic-parameter" type="dynamicParameterType" maxOccurs="unbounded"/>									</xs:sequence>								</xs:complexType>							</xs:element>						</xs:sequence>					</xs:complexType>				</xs:element>				<xs:element name="run-state" minOccurs="0">					<xs:complexType>						<xs:sequence>							<xs:element name="max-innovation-id" type="xs:short"/>						</xs:sequence>					</xs:complexType>				</xs:element>				<xs:element name="generation">					<xs:complexType>						<xs:sequence>							<xs:element name="generation-info">								<xs:complexType>									<xs:sequence>										<xs:element name="save-time" type="xs:dateTime"/>										<xs:element name="max-fitness" type="xs:decimal"/>										<xs:element name="min-fitness" type="xs:decimal"/>										<xs:element name="avg-fitness" type="xs:decimal"/>										<xs:element name="species-count" type="xs:short"/>									</xs:sequence>								</xs:complexType>							</xs:element>							<xs:element name="specie">								<xs:complexType>									<xs:sequence>										<xs:element name="specie-info">											<xs:complexType>												<xs:sequence>													<xs:element name="age" type="xs:short"/>													<xs:element name="max-fitness" type="xs:decimal"/>													<xs:element name="min-fitness" type="xs:decimal"/>													<xs:element name="avg-fitness" type="xs:decimal"/>												</xs:sequence>											</xs:complexType>										</xs:element>										<xs:element name="genome" maxOccurs="unbounded">											<xs:complexType>												<xs:sequence>													<xs:element name="nodes">														<xs:complexType>															<xs:sequence>																<xs:element name="node" minOccurs="0" maxOccurs="unbounded">																	<xs:complexType>																		<xs:attribute name="id" type="xs:integer" use="required"/>																		<xs:attribute name="type" use="required">																			<xs:simpleType>																				<xs:restriction base="xs:token">																					<xs:enumeration value="bias"/>																					<xs:enumeration value="hid"/>																					<xs:enumeration value="in"/>																					<xs:enumeration value="out"/>																				</xs:restriction>																			</xs:simpleType>																		</xs:attribute>																	</xs:complexType>																</xs:element>															</xs:sequence>														</xs:complexType>													</xs:element>													<xs:element name="connections">														<xs:complexType>															<xs:sequence>																<xs:element name="connection" minOccurs="0" maxOccurs="unbounded">																	<xs:complexType>																		<xs:attribute name="innov-id" type="xs:integer" use="required"/>																		<xs:attribute name="src-id" type="xs:integer" use="required"/>																		<xs:attribute name="tgt-id" type="xs:integer" use="required"/>																		<xs:attribute name="enabled" type="xs:boolean" use="required"/>																		<xs:attribute name="weight" type="xs:decimal" use="required"/>																	</xs:complexType>																</xs:element>															</xs:sequence>														</xs:complexType>													</xs:element>												</xs:sequence>												<xs:attribute name="id" type="xs:integer" use="required"/>												<xs:attribute name="fitness" type="xs:decimal" use="required"/>												<xs:attribute name="primary-parent-id" type="xs:integer" use="required"/>												<xs:attribute name="secondary-parent-id" type="xs:integer" use="required"/>											</xs:complexType>										</xs:element>									</xs:sequence>									<xs:attribute name="id" type="xs:integer" use="required"/>									<xs:attribute name="size" type="xs:short" use="required"/>								</xs:complexType>							</xs:element>						</xs:sequence>						<xs:attribute name="id" type="xs:integer" use="required"/>					</xs:complexType>				</xs:element>			</xs:sequence>		</xs:complexType>	</xs:element></xs:schema>
<!-- neodl5.grp.bf1.yahoo.com Sat Oct 26 14:53:59 UTC 2019 -->

=== colgreen/neat-yahoo-group-archive/files/NEAT XML/neat-run-output.xml
<neat-run-output xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\neat\neat-run-output.xsd">
	<!-- The general philosophy here is to show pertinent data copied verbatim from the neat-run-config file.
     This allows us to determine the domian and experimental parameters that generated the output. However this
     data isn't strictly necessary so we allow each of the blocks to be optional
      -->
	<!-- Optional block -->
	<!-- A copy of the neat-run-info xml block from the neat-run-config file -->
	<neat-run-info>
		<author>Mr Foo Bar</author>
		<description>Experiment to determine relationship between connection-mutation-rate and complexification. Test run 1 of 10</description>
	</neat-run-info>
	<!-- Optional block -->
	<!-- A copy of the search-parameters xml block from the neat-run-config file -->
	<search-parameters>
		<population-size>10</population-size>
		<neuron-mutation-probability>0.02</neuron-mutation-probability>
		<connect-mutation-probability>0.04</connect-mutation-probability>
		<weight-mutation-probability>0.75</weight-mutation-probability>
		<compatibility-threshold>9.0</compatibility-threshold>
		<disjoint-coefficient>1.0</disjoint-coefficient>
		<excess-coefficient>1.0</excess-coefficient>
		<weightdelta-coefficient>7.0</weightdelta-coefficient>
		<survival-proportion>0.1</survival-proportion>
		<!-- For experimental purposes we allow dynamic search parameters to be specified -->
		<dynamic-parameter id="searchparam1">1234</dynamic-parameter>
		<dynamic-parameter id="searchparam2">1235</dynamic-parameter>
	</search-parameters>
	<!-- Optional Block -->
	<!-- A copy of the domain-config xml block from the neat-run-config file -->
	<domain-config>
		<domain-id id="DereksTicTacToe_variation99" version="1.01" authoreddate="01/01/2004">Derek's Implemetation of a Tic-Tac-Toe environment</domain-id>
		<domain-parameters>
			<input-node-count>10</input-node-count>
			<output-node-count>10</output-node-count>
			<!-- For experimental purposes we allow dynamic domain parameters to be specified -->
			<dynamic-parameter id="domainparam1">1234</dynamic-parameter>
			<dynamic-parameter id="domainparam2">1235</dynamic-parameter>
		</domain-parameters>
	</domain-config>
	<!-- Now we output some data that describes the NEAT engine's state and also the current population. -->
	<run-state>
		<!-- keep track of innovation num in case we wish to restart the run? -->
		<max-innovation-id>12345</max-innovation-id>
	</run-state>
	<!-- The dialect allows for outputting all generations, just the last one or a subset of all generations -->
	<generation id="1">
		<generation-info>
			<save-time>2002-05-30T09:00:00</save-time>
			<max-fitness>234</max-fitness>
			<min-fitness>123</min-fitness>
			<avg-fitness>222</avg-fitness>
			<species-count>5</species-count>
		</generation-info>
		<specie id="1" size="2">
			<specie-info>
				<age>5</age>
				<max-fitness>234</max-fitness>
				<min-fitness>123</min-fitness>
				<avg-fitness>222</avg-fitness>
			</specie-info>
			<genome id="1" fitness="110" primary-parent-id="5" secondary-parent-id="2">
				<nodes>
					<node id="0" type="bias"/>
					<node id="1" type="in"/>
					<node id="2" type="in"/>
					<node id="3" type="out"/>
					<node id="4" type="hid"/>
				</nodes>
				<connections>
					<connection innov-id="4" src-id="0" tgt-id="3" enabled="1" weight="-1.3731676929130425"/>
					<connection innov-id="5" src-id="0" tgt-id="3" enabled="1" weight="+0.4"/>
				</connections>
			</genome>
			<genome id="2" fitness="100" primary-parent-id="12" secondary-parent-id="13">
				<nodes>
					<node id="0" type="bias"/>
					<node id="1" type="in"/>
					<node id="2" type="in"/>
					<node id="3" type="out"/>
					<node id="4" type="hid"/>
				</nodes>
				<connections>
					<connection innov-id="4" src-id="0" tgt-id="3" enabled="1" weight="-1.3731676929130425"/>
					<connection innov-id="5" src-id="0" tgt-id="3" enabled="1" weight="+0.4"/>
				</connections>
			</genome>
		</specie>
	</generation>
</neat-run-output>

<!-- neodl3.grp.bf1.yahoo.com Sat Oct 26 14:54:00 UTC 2019 -->
